### ISSUE TITLE
Using Annotation tool to Annotate Custom Dataset

### ISSUE THREAD

**Issue by dhirajsuvarna** [daerduoCarey/partnet_anno_system#7]
Hi,

I am trying to use this Annotation Tool to annotate some CAD 3D Models.

I have been able to get this tool up and running on Windows enviornment. 
However, I am not able to figure out how to use this tool on my custom 3D Models. 

Following are my three questions - 
1. How do I load my 3D Models into the UI of the tool
2. How do I define my custom segment categories.

Also, would like to know the significance of folders and files under `./storage/data/Bed/{guiid}/`
- there are multiple `obj` files which are created, each corresponding to a single instance of the segments. Has these segments been created by the tool or we have to create it manually?
- there are also other files {guiid}.json
- leaf_part_ids.json
- normalization_params.txt
- tree_hier.json

3. Do I need to create the files for my dataset? 

I would appreciate any help on my queries.

**Comment by daerduoCarey** [comment]
1.
just put your data in the `storage/data` folder. You should mimic the given examples. Otherwise, you might need to change the UI code a bit to read your new data format.
2.
PartNet data has natural categories, e.g. chairs, tables, and every model within the same category will be asked to follow the same pre-defined semantic-hierarchy. If you haven't watch this video, please watch to get more understanding: https://www.youtube.com/watch?v=7pEuoxmb-MI. If your data has no category, you can make a degraded tree template (and put a json file here https://github.com/daerduoCarey/partnet_anno_system/tree/master/server/public/part_hier_templates) and a trivial class, e.g. "no-class". you might need to import the new "no-class" category into the MySQL/the system.

- the obj files in `leaf_part_obj_normalized` provide initial segmentations so if you check the PartNet video, you will see some parts can be easily annotated by selecting the initial parts. It's also OK to have 1 obj file to be the entire shape as its whole. But this will make everything depends on cutting. If you can use some heuristics (e.g mesh connectivities, connected components) to figure out some initial segments, this will use less cutting of the mesh.
- `leaf_part_ids.json` summarizes the obj file names to load
- `leaf_part_obj` and `normalization_params.txt` store the pre-normalized data, which is not loaded by the UI. For your new data, you need to normalize it into a unit-sphere so that the UI can correctly display it. You normalize your data into `leaf_part_obj_normalized` obj files. 
- `tree_hier.json` you can ignore this.
3. 
Yes, unless you are happy to edit the UI code for your new data format.

**Comment by dhirajsuvarna** [comment]
@daerduoCarey, Thank You for you quick response. 
It seems I have to understand and modify the code to make it work on my custom dataset. 

Though my knowldege on javascript is pretty basic, I will try to do this sometime in future. 
However, for now, do you know of any tool which will help me create segmented data for my custom dataset.

**Comment by daerduoCarey** [comment]
You can run simple graph-based connected component detection. Say, you figure out the face-group by if there is an edge connecting any two faces in the group.
